### ISSUE TITLE
LazyLoadImageDirective Can't resolve all parameters for LazyLoadImageDirective: (?, [object Object], [object Object])

### ISSUE THREAD

**Issue by mdenissov** [tjoskar/ng-lazyload-image#183]
Hi!

Error after update to ng-lazyload-image@3.2.1.

```
"Error: Can't resolve all parameters for LazyLoadImageDirective: (?, [object Object], [object Object]).
    at SyntaxError.ZoneAwareError (http://localhost:4200/vendor.bundle.js:46919:33)
    at SyntaxError.BaseError [as constructor] (http://localhost:4200/vendor.bundle.js:63901:16)
    at new SyntaxError (http://localhost:4200/vendor.bundle.js:83723:16)
    at CompileMetadataResolver.webpackJsonp.../../../compiler/src/metadata_resolver.js.CompileMetadataResolver._getDependenciesMetadata (http://localhost:4200/vendor.bundle.js:69966:31)
    at CompileMetadataResolver.webpackJsonp.../../../compiler/src/metadata_resolver.js.CompileMetadataResolver._getTypeMetadata (http://localhost:4200/vendor.bundle.js:69841:26)
    at CompileMetadataResolver.webpackJsonp.../../../compiler/src/metadata_resolver.js.CompileMetadataResolver.getNonNormalizedDirectiveMetadata (http://localhost:4200/vendor.bundle.js:69481:24)
    at CompileMetadataResolver.webpackJsonp.../../../compiler/src/metadata_resolver.js.CompileMetadataResolver._loadDirectiveMetadata (http://localhost:4200/vendor.bundle.js:69357:23)
    at http://localhost:4200/vendor.bundle.js:69558:54
    at Array.forEach (<anonymous>)
    at CompileMetadataResolver.webpackJsonp.../../../compiler/src/metadata_resolver.js.CompileMetadataResolver.loadNgModuleDirectiveAndPipeMetadata (http://localhost:4200/vendor.bundle.js:69557:41)
    at http://localhost:4200/vendor.bundle.js:68431:58
    at Array.forEach (<anonymous>)
    at JitCompiler.webpackJsonp.../../../compiler/src/jit/compiler.js.JitCompiler._loadModules (http://localhost:4200/vendor.bundle.js:68430:43)
    at JitCompiler.webpackJsonp.../../../compiler/src/jit/compiler.js.JitCompiler._compileModuleAndComponents (http://localhost:4200/vendor.bundle.js:68385:52)
    at JitCompiler.webpackJsonp.../../../compiler/src/jit/compiler.js.JitCompiler.compileModuleAsync (http://localhost:4200/vendor.bundle.js:68351:21)"
```

**Comment by rimlin** [comment]
Hi, which Angular version you use?

**Comment by mdenissov** [comment]
ng -v
    _                      _                 ____ _     ___
   / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
  / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
 / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
/_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
               |___/
@angular/cli: 1.2.3
node: 8.2.1
os: darwin x64
@angular/common: 2.4.10
@angular/compiler: 2.4.10
@angular/core: 2.4.10
@angular/forms: 2.4.10
@angular/http: 2.4.10
@angular/platform-browser: 2.4.10
@angular/platform-browser-dynamic: 2.4.10
@angular/router: 3.4.10
@angular/cli: 1.2.3
@angular/compiler-cli: 2.4.10

{
  "name": "sm-web",
  "version": "0.0.0",
  "license": "MIT",
  "angular-cli": {},
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "lint": "tslint \"src/**/*.ts\"",
    "test": "ng test",
    "pree2e": "webdriver-manager update --standalone false --gecko false",
    "e2e": "protractor"
  },
  "private": true,
  "dependencies": {
    "@angular/common": "^2.3.1",
    "@angular/compiler": "^2.3.1",
    "@angular/core": "^2.3.1",
    "@angular/forms": "^2.3.1",
    "@angular/http": "^2.3.1",
    "@angular/platform-browser": "^2.3.1",
    "@angular/platform-browser-dynamic": "^2.3.1",
    "@angular/router": "^3.3.1",
    "angular2-materialize": "^15.0.4",
    "angular2-text-mask": "^8.0.0",
    "core-js": "^2.4.1",
    "file-loader": "^0.11.2",
    "hammerjs": "^2.0.8",
    "jquery": "^2.2.4",
    "materialize-css": "^0.98.2",
    "ng-lazyload-image": "3.1.0",
    "ng2-bootstrap": "^1.4.0",
    "ng2-translate": "^5.0.0",
    "rxjs": "^5.0.1",
    "ts-helpers": "^1.1.1",
    "webpack": "^3.3.0",
    "zone.js": "^0.7.2"
  },
  "devDependencies": {
    "@angular/cli": "^1.2.0",
    "@angular/compiler-cli": "^2.3.1",
    "@types/jasmine": "2.5.38",
    "@types/node": "^6.0.42",
    "codelyzer": "~2.0.0-beta.1",
    "jasmine-core": "2.5.2",
    "jasmine-spec-reporter": "2.5.0",
    "karma": "1.2.0",
    "karma-chrome-launcher": "^2.0.0",
    "karma-cli": "^1.0.1",
    "karma-jasmine": "^1.0.2",
    "karma-remap-istanbul": "^0.2.1",
    "protractor": "~4.0.13",
    "ts-node": "1.2.1",
    "tslint": "^4.0.2",
    "typescript": "~2.0.3"
  }
}

**Comment by rimlin** [comment]
Ok, I'll try to fix it.
I think that the problem is relative with injection of `PLATFORM_ID`, because `PLATFORM_ID` introduced in Angular 4.
@tjoskar i think here 2 way to resolve problem:

1. Continue disable module in server side. To support Angular 2 need another approach to disable module in server side in Angular 4. Also with Angular 2 can be used Angular Universal solution to server side rendering Angular 2 apps.
2. First of all, disabling module in server was a consequence of error in https://github.com/tjoskar/ng-lazyload-image/issues/178. Maybe just need add more conditions and catches to [lazyload-image.ts](https://github.com/tjoskar/ng-lazyload-image/blob/master/src/lazyload-image.ts) to prevent throwing errors in server side?

**Comment by tjoskar** [comment]
Good catch @rimlin! Instead of using PLATFORM_ID we could check if window is defined. I.e. `if (typeof window !== 'undefined') return`. 
What do you think?

**Comment by rimlin** [comment]
Good idea, @tjoskar! I will check it today.

**Comment by rimlin** [comment]
https://github.com/tjoskar/ng-lazyload-image/pull/184

**Comment by tjoskar** [comment]
@mdenissov, can you install `ng-lazyload-image@3.2.2` to see if it fix the issue?

**Comment by mdenissov** [comment]
@tjoskar It's work!

**Comment by tjoskar** [comment]
Thanks @rimlin
